### PR TITLE
Change ChatEngine#create to ChatEngineCore#create

### PR DESCRIPTION
**Pull request by samiahmedsiddiqui**
I think, it should be linked to https://www.pubnub.com/docs/chat-engine/global#chatenginecore as the ChatEngineCore is the Global Object to create the ChatEngine instance..

### CODE REVIEW

**Comment by ianjennings** [comment]
Hrm, tests still not passing. It's trying to make requests to:
https://pubsub.pubnub.com/v1/blocks/sub-key/undefined/chat-engine-server

**Comment by ianjennings** [comment]
Upon review, the info in this pull is incorrect. ChatEngineCore create is correct.
https://www.pubnub.com/docs/chat-engine/global

**Comment by ianjennings** [comment]
This was outdated so I duplicated it in another pull. 
https://github.com/pubnub/chat-engine/pull/354

**Comment by samiahmedsiddiqui** [comment]
Thanks @ianjennings 😄

**Comment by ianjennings** [comment]
You got it @samiahmedsiddiqui :)

**Pull request closed without merging**
