### PR TITLE
Online events tests + properly update chat.users 

### PR DESCRIPTION
**Pull request by ianjennings**
What this fixes:

1. Fixes ```chat.users``` is not immediately updated with new users from ```$.online.* events```
2. Fixes ```chat.users``` persists users that should be removed from ```$.offline.*``` events
3. Exposes calling ```chat.leave()``` always results in ```$.offline.disconnect``` (it should fire $.offline.leave). See https://support.pubnub.com/support/solutions/articles/14000043547-do-client-disconnects-trigger-leave-events-

### CODE REVIEW

**Comment by ianjennings** [comment]
* the unsubscribe should create the leave event but there are some configs to consider on the SDK and the server (the keys)
* assuming latest JS SDK, the leave events are enabled
* see TCP_FIN property in Presence add-on

**Comment by AdamTyler** [comment]
I'm noticing that calling `chat.leave()` isn't firing an event on other connected users sessions. I eventually see the `$.offline.disconnect` but never the `$.offline.leave`.

Should this issue be addressing that or should I open a new ticket?

**Comment by ianjennings** [comment]
@AdamTyler This issue will be addressing that. That's actually what's blocking it from being merged.

**Comment by ianjennings** [comment]
Continuing in #297

**Pull request closed without merging**
